import {
  LoginScreen,
  SelectLoginScreenFromHaveRide,
  LoginScreenFromHaveRide,
  SetYourLocation,
  SignupScreen,
  ForgetPassScreen,
  GetStartedScreen,
  RideScreen,
  SelectLogin,
  Becomeadriverone,
  Becomeadrivertwo,
  Becomeadriverthree,
  Becomeadriverfour,
  DriverRideTypeScreen,
  DriverRideRequestScreen,
  DriverRideRequestScreenTwo,
  DriverRideStart,
  YouAreOnWayFromDriverScreen,
  YouAreOnDestinationFromDriverScreen,
  SoloRidesFromDriverRideTypeScreen,
  WaytoPickupFromSoloRidesScreenTwo,
  YouAreOnWayFromSoloDriverScreen,
  YouAreOnDestinationFromSoloDriverScreen,
  PAymentFromSoloDriverScreen,
  RideHistoryFromDriverSoloRidesScreen,
  RideHistoryFromDriverSoloRidesScreentwo,
  FAQFromDriverSoloRidesScreen,
  RatingsReviewsFromDriverSoloRidesScreen,
  MyIncomeFromDriverSoloRidesScreen,
  YourRideStartFromSoloDriverScreen,
  HomeScreen,
  Carscreen,
  SoloRidesScreens,
  SoloRidesScreensTwo,
  YourRidesInProcess,
  YourRidesInProcessTwo,
  FindingCaptainScreen,
  FindingCaptainScreenFromSolo,
  CancelUserScreen,
  OnliineSoloRide,
  RideRequest,
  ReportScreen,
  PAymentScreen,
  PaymentFromDriverSwitchToRideSharingScreen,
  LogoutScreen,
  PickupDropoffCard,
  DropofflocationScreen,
  DropOffLocationFromSoloScreen,
  FindingCaptainScreenFromFixedRoutes,
  DriverOnWayFromFixedScreen,
  RideProcessFromFixedScreen,
  PaymentFeedbackFromFixedScreen,
  SelectRideScreenFromSolo,
  SelectRideScreenFromSoloParams,
  DriverOnWayFromSoloScreen,
  RideProcessScreenFromSolo,
  PaymentFeedbackScreenFromSolo,
  ReportFromSoloDriverScreen,
  ReportFromDriverSwitchToRideSharingScreen,
  RideHistoryScreen,
  FixedRouteScreen,
  RideProcessScreen,
  MessageScreen,
  MessageFromSoloScreen,
  RideHistoryScreenTwo,
  SelectRideScreen,
  DriveronwayScreen,
  PaymentFeedbackScreen,
  RideShareScreen,
  ChooseRideScreen,
  DriverInformationScreen,
  CurrentRideSeatScreen,
  OnthewayScreen,
  ArrievedDestinationScreen,
  RideRequestTwo,
  RideDeetailsScreen,
  FixedRouteScreenTwo,
  ChangePasswordScreen,
  AddtowalletScreen,
  UserAddCreditScreen,
  DriverAddCreditScreen,
  FAQScreen,
  RatingsAndReviewsScreen,
  EnterEmailScreen,
  OpenMailScreen,
} from '../screens';
//import {GetStartedScreen} from '../screens/GetStartedPhone';

export const AuthStack = [
  {
    name: 'RideScreen',
    component: RideScreen,
    key: 'RideScreen',
  },
  {
    name: 'SetYourLocation',
    component: SetYourLocation,
    key: 'SetYourLocation',
  },
  {
    name: 'LoginScreen',
    component: LoginScreen,
    key: 'LoginScreen',
  },
  {
    name: 'SelectLoginScreenFromHaveRide',
    component: SelectLoginScreenFromHaveRide,
    key: 'SelectLoginScreenFromHaveRide',
  },
  {
    name: 'LoginScreenFromHaveRide',
    component: LoginScreenFromHaveRide,
    key: 'LoginScreenFromHaveRide',
  },
  {
    name: 'SignupScreen',
    component: SignupScreen,
    key: 'SignupScreen',
  },
  {
    name: 'ForgetPassScreen',
    component: ForgetPassScreen,
    key: 'ForgetPassScreen',
  },
  {
    name: 'GetStartedScreen',
    component: GetStartedScreen,
    key: 'GetStartedScreen',
  },
  {
    name: 'SelectLogin',
    component: SelectLogin,
    key: 'SelectLogin',
  },

  {
    name: 'Becomeadriverone',
    component: Becomeadriverone,
    key: 'Becomeadriverone',
  },
  {
    name: 'Becomeadrivertwo',
    component: Becomeadrivertwo,
    key: 'Becomeadrivertwo',
  },
  {
    name: 'YourRidesInProcess',
    component: YourRidesInProcess,
    key: 'YourRidesInProcess',
  },
  {
    name: 'YourRidesInProcessTwo',
    component: YourRidesInProcessTwo,
    key: 'YourRidesInProcessTwo',
  },
  {
    name: 'FindingCaptainScreen',
    component: FindingCaptainScreen,
    key: 'FindingCaptainScreen',
  },
  {
    name: 'FindingCaptainScreenFromSolo',
    component: FindingCaptainScreenFromSolo,
    key: 'FindingCaptainScreenFromSolo',
  },
  {
    name: 'CancelUserScreen',
    component:  CancelUserScreen,
    key: 'CancelUserScreen',
  },
  {
    name: 'FindingCaptainScreenFromFixedRoutes',
    component:  FindingCaptainScreenFromFixedRoutes,
    key: 'FindingCaptainScreenFromFixedRoutes',
  },
  {
    name: 'DriverOnWayFromFixedScreen',
    component:  DriverOnWayFromFixedScreen,
    key: 'DriverOnWayFromFixedScreen',
  },
  {
    name: 'RideProcessFromFixedScreen',
    component:  RideProcessFromFixedScreen,
    key: 'RideProcessFromFixedScreen',
  },
  {
    name: 'PaymentFeedbackFromFixedScreen',
    component:  PaymentFeedbackFromFixedScreen,
    key: 'PaymentFeedbackFromFixedScreen',
  },
  {
    name: 'Becomeadriverthree',
    component: Becomeadriverthree,
    key: 'Becomeadriverthree',
  },
  {
    name: 'Becomeadriverfour',
    component: Becomeadriverfour,
    key: 'Becomeadriverfour',
  },
  {
    name: 'DriverRideTypeScreen',
    component: DriverRideTypeScreen,
    key: 'DriverRideTypeScreen',
  },
  {
    name: 'DriverRideRequestScreen',
    component: DriverRideRequestScreen,
    key: 'DriverRideRequestScreen',
  },
  {
    name: 'DriverRideRequestScreenTwo',
    component: DriverRideRequestScreenTwo,
    key: 'DriverRideRequestScreenTwo',
  },
  {
    name: 'DriverRideStart',
    component: DriverRideStart,
    key: 'DriverRideStart',
  },
  {
    name: 'PickupDropoffCard',
    component: PickupDropoffCard,
    key: 'PickupDropoffCard',
  },
  {
    name: 'YouAreOnWayFromDriverScreen',
    component: YouAreOnWayFromDriverScreen,
    key: 'YouAreOnWayFromDriverScreen',
  },
  {
    name: 'YouAreOnDestinationFromDriverScreen',
    component: YouAreOnDestinationFromDriverScreen,
    key: 'YouAreOnDestinationFromDriverScreen',
  },
   {
    name: 'SoloRidesFromDriverRideTypeScreen',
    component:  SoloRidesFromDriverRideTypeScreen,
    key: 'SoloRidesFromDriverRideTypeScreen',
  },
  {
    name: 'WaytoPickupFromSoloRidesScreenTwo',
    component:  WaytoPickupFromSoloRidesScreenTwo,
    key: 'WaytoPickupFromSoloRidesScreenTwo',
  },
  {
    name: 'YouAreOnWayFromSoloDriverScreen',
    component:  YouAreOnWayFromSoloDriverScreen,
    key: 'YouAreOnWayFromSoloDriverScreen',
  },
  {
    name: 'YouAreOnDestinationFromSoloDriverScreen',
    component:  YouAreOnDestinationFromSoloDriverScreen,
    key: 'YouAreOnDestinationFromSoloDriverScreen',
  },
  {
    name: 'PAymentFromSoloDriverScreen',
    component:  PAymentFromSoloDriverScreen,
    key: 'PAymentFromSoloDriverScreen',
  },
  {
    name: 'ReportFromSoloDriverScreen',
    component:  ReportFromSoloDriverScreen,
    key: 'ReportFromSoloDriverScreen',
  },
  {
    name: 'ReportFromDriverSwitchToRideSharingScreen',
    component:   ReportFromDriverSwitchToRideSharingScreen,
    key: 'ReportFromDriverSwitchToRideSharingScreen',
  },
  {
    name: 'RideHistoryFromDriverSoloRidesScreen',
    component:  RideHistoryFromDriverSoloRidesScreen,
    key: 'RideHistoryFromDriverSoloRidesScreen',
  },
  {
    name: 'RideHistoryFromDriverSoloRidesScreentwo',
    component:  RideHistoryFromDriverSoloRidesScreentwo,
    key: 'RideHistoryFromDriverSoloRidesScreentwo',
  },
  {
    name: 'FAQFromDriverSoloRidesScreen',
    component:  FAQFromDriverSoloRidesScreen,
    key: 'FAQFromDriverSoloRidesScreen',
  },
  {
    name: 'RatingsReviewsFromDriverSoloRidesScreen',
    component:  RatingsReviewsFromDriverSoloRidesScreen,
    key: 'RatingsReviewsFromDriverSoloRidesScreen',
  },
  {
    name: 'MyIncomeFromDriverSoloRidesScreen',
    component:  MyIncomeFromDriverSoloRidesScreen,
    key: 'MyIncomeFromDriverSoloRidesScreen',
  },
  {
    name: 'YourRideStartFromSoloDriverScreen',
    component: YourRideStartFromSoloDriverScreen,
    key: 'YourRideStartFromSoloDriverScreen',
  },
  {
    name: 'HomeScreen',
    component: HomeScreen,
    key: 'HomeScreen',
  },
  {
    name: 'Carscreen',
    component: Carscreen,
    key: 'Carscreen',
  },
  {
    name: 'SoloRidesScreens',
    component: SoloRidesScreens,
    key: 'SoloRidesScreens',
  },
  {
    name: 'SoloRidesScreensTwo',
    component: SoloRidesScreensTwo,
    key: 'SoloRidesScreensTwo',
  },
  {
    name: 'OnliineSoloRide',
    component: OnliineSoloRide,
    key: 'OnliineSoloRide',
  },
  {
    name: 'RideRequest',
    component: RideRequest,
    key: 'RideRequest',
  },
  {
    name: 'ReportScreen',
    component: ReportScreen,
    key: 'ReportScreen',
  },
  {
    name: 'PAymentScreen',
    component: PAymentScreen,
    key: 'PAymentScreen',
  },
  {
    name: 'PaymentFromDriverSwitchToRideSharingScreen',
    component: PaymentFromDriverSwitchToRideSharingScreen,
    key: 'PaymentFromDriverSwitchToRideSharingScreen',
  },
  {
    name: 'LogoutScreen',
    component: LogoutScreen,
    key: 'LogoutScreen',
  },
  {
    name: 'DropofflocationScreen',
    component: DropofflocationScreen,
    key: 'DropofflocationScreen',
  },
  {
    name: 'DropOffLocationFromSoloScreen',
    component: DropOffLocationFromSoloScreen,
    key: 'DropOffLocationFromSoloScreen',
  },
  {
    name: 'RideProcessScreenFromSolo',
    component: RideProcessScreenFromSolo,
    key: 'RideProcessScreenFromSolo',
  },
  {
    name: 'PaymentFeedbackScreenFromSolo',
    component: PaymentFeedbackScreenFromSolo,
    key: 'PaymentFeedbackScreenFromSolo',
  },
  {
    name: 'RideHistoryScreen',
    component: RideHistoryScreen,
    key: 'RideHistoryScreen',
  },
  {
    name: 'FixedRouteScreen',
    component: FixedRouteScreen,
    key: 'FixedRouteScreen',
  },
  {
    name: 'RideProcessScreen',
    component: RideProcessScreen,
    key: 'RideProcessScreen',
  },
  {
    name: 'MessageScreen',
    component: MessageScreen,
    key: 'MessageScreen',
  },
  {
    name: 'MessageFromSoloScreen',
    component: MessageFromSoloScreen,
    key: 'MessageFromSoloScreen',
  },
  {
    name: 'RideHistoryScreenTwo',
    component: RideHistoryScreenTwo,
    key: 'RideHistoryScreenTwo',
  },
  {
    name: 'SelectRideScreen',
    component: SelectRideScreen,
    key: 'SelectRideScreen',
  },
  {
    name: 'SelectRideScreenFromSolo',
    component: SelectRideScreenFromSolo,
    key: 'SelectRideScreenFromSolo',
  },
  {
    name: 'SelectRideScreenFromSoloParams',
    component: SelectRideScreenFromSoloParams,
    key: 'SelectRideScreenFromSoloParams',
  },
  {
    name: 'DriveronwayScreen',
    component: DriveronwayScreen,
    key: 'DriveronwayScreen',
  },
  {
    name: 'DriverOnWayFromSoloScreen',
    component: DriverOnWayFromSoloScreen,
    key: 'DriverOnWayFromSoloScreen',
  },
  {
    name: 'PaymentFeedbackScreen',
    component: PaymentFeedbackScreen,
    key: 'PaymentFeedbackScreen',
  },
  {
    name: 'RideShareScreen',
    component: RideShareScreen,
    key: 'RideShareScreen',
  },
  {
    name: 'ChooseRideScreen',
    component: ChooseRideScreen,
    key: 'ChooseRideScreen',
  },
  {
    name: 'DriverInformationScreen',
    component: DriverInformationScreen,
    key: 'DriverInformationScreen',
  },
  {
    name: 'CurrentRideSeatScreen',
    component: CurrentRideSeatScreen,
    key: 'CurrentRideSeatScreen',
  },
  {
    name: 'OnthewayScreen',
    component: OnthewayScreen,
    key: 'OnthewayScreen',
  },
  {
    name: 'ArrievedDestinationScreen',
    component: ArrievedDestinationScreen,
    key: 'ArrievedDestinationScreen',
  },
  {
    name: 'RideRequestTwo',
    component: RideRequestTwo,
    key: 'RideRequestTwo',
  },
  {
    name: 'RideDeetailsScreen',
    component: RideDeetailsScreen,
    key: 'RideDeetailsScreen',
  },
  {
    name: 'FixedRouteScreenTwo',
    component: FixedRouteScreenTwo,
    key: 'FixedRouteScreenTwo',
  },
  {
    name: 'ChangePasswordScreen',
    component: ChangePasswordScreen,
    key: 'ChangePasswordScreen',
  },
  {
    name: 'AddtowalletScreen',
    component: AddtowalletScreen,
    key: 'AddtowalletScreen',
  },
  {
    name: 'UserAddCreditScreen',
    component: UserAddCreditScreen,
    key: 'UserAddCreditScreen',
  },
  {
    name: 'DriverAddCreditScreen',
    component: DriverAddCreditScreen,
    key: 'DriverAddCreditScreen',
  },
  {
    name: 'FAQScreen',
    component: FAQScreen,
    key: 'FAQScreen',
  },
  {
    name: 'RatingsAndReviewsScreen',
    component: RatingsAndReviewsScreen,
    key: 'RatingsAndReviewsScreen',
  },
  {
    name: 'EnterEmailScreen',
    component: EnterEmailScreen,
    key: 'EnterEmailScreen',
  },
  {
    name: 'OpenMailScreen',
    component: OpenMailScreen,
    key: 'OpenMailScreen',
  },
];
